name = "MutualInformationImageRegistration"
uuid = "f55eb597-e6a1-4806-8966-600fcb3de930"
authors = ["Octogonapus <firey45@gmail.com> and contributors"]
version = "0.1.1"

[deps]
FastHistograms = "06971c4e-2824-4b19-bcf3-55442efb9bc7"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
FastHistograms = "0.2"
OffsetArrays = "1.4"
julia = "1.5"
